name: Node.js CI workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: CI
    uses: merlusorg/GHA.workflows/.github/workflows/gha.workflows.build-node.yml@main
